name: ci

on:
  push:
    branches:
      - master
      - main

jobs:
    build-deploy:
        name: Build and deploy the documentation
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with: 
                submodules: true

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y make
                python -m pip install -U pip
                pip install -r requirements.txt
                pip install ghp-import
            
            - name: Build
              run: |
                cd docs
                make html

            - name: Deploy on the branch gh-pages
              run: |
                ghp-import -n -f -p ./docs/_build/html
              